version: "3"
services:
  web:
    container_name: flask-blog
    build: .
    ports:
      - "0.0.0.0:5000:5000"
    command: bash -c  "python run.py"

    volumes:
      - .:/code
    stdin_open: true
    tty: true
